name: RenameUI
main: RenameUI\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

commands:
  rename:
    description: Open Rename UI
    permission: renameui.command

permissions:
  renameui.command:
    default: true
  renameui.use:
    default: true
  renameui.bypass:
    default: op
